  "recommendations" = """
  [
    "davidanson.vscode-markdownlint",
    "dbaeumer.vscode-eslint",
    "eamodio.gitlens",
    "meganrogge.template-string-converter",
    "mikestead.dotenv",
    "ms-vscode.vscode-typescript-next",
    "pkief.material-icon-theme",
    "shardulm94.trailing-spaces"
  ]
"""
"unwantedRecommendations" = """
  [
    // VSCode has implemented an optimized version
    "coenraads.bracket-pair-colorizer",
    "coenraads.bracket-pair-colorizer-2",
    // Lots of conflicts
    "esbenp.prettier-vscode",
    // Replaced by ESLint
    "eg2.tslint",
    "ms-vscode.vscode-typescript-tslint-plugin",
    // Not configurable per workspace, tends to conflict with other linters
    // Use eslint-plugin-sonarjs for JS/TS projects
    "sonarsource.sonarlint-vscode"
  ]
"""

"editor.rulers" = "[80,120]"
"[git-commit]" = """
  {
    "editor.rulers": [
      72
    ]
  }
"""
"editor.detectIndentation" = "false"
"editor.tabSize" = "2"
"editor.formatOnSave" = "true"
"editor.codeActionsOnSave" = """
  {
    "source.fixAll": true,
    "source.organizeImports": true
  }
"""
# Set the default formatter to help avoid Prettier
"[json]" = """
  {
    "editor.defaultFormatter": "dbaeumer.vscode-eslint"
  }
"""
"[jsonc]" = """
  {
    "editor.defaultFormatter": "dbaeumer.vscode-eslint"
  }
"""
"[html]" = """
  {
    "editor.defaultFormatter": "dbaeumer.vscode-eslint"
  }
"""
"[javascript]" = """
  {
    "editor.defaultFormatter": "dbaeumer.vscode-eslint"
  }
"""
"[javascriptreact]" = """
  {
    "editor.defaultFormatter": "dbaeumer.vscode-eslint"
  }
"""
"[typescript]" = """
  {
    "editor.defaultFormatter": "dbaeumer.vscode-eslint"
  }
"""
"[typescriptreact]" = """
  {
    "editor.defaultFormatter": "dbaeumer.vscode-eslint"
  }
"""
"javascript.preferences.quoteStyle" = "\"single\""
"typescript.preferences.quoteStyle" = "\"single\""
"html.format.wrapAttributes" = "\"force-expand-multiline\""
"typescript.tsdk" = "\"./tournament-scheduler/node_modules/typescript/lib\""
"javascript.format.semicolons" = "\"remove\""
"typescript.format.semicolons" = "\"remove\""
"javascript.preferences.importModuleSpecifier" = "\"non-relative\""
"typescript.preferences.importModuleSpecifier" = "\"non-relative\""
"eslint.validate" = """
  [
    "typescript",
    "typescriptreact"
  ]
"""
"eslint.workingDirectories" = """
  [
    {
      "mode": "auto"
    }
  ]
"""
"eslint.rules.customizations" = """
  [
    {
      "rule": "*",
      "severity": "downgrade"
    }
  ]
"""
"files.insertFinalNewline" = "true"
"trailing-spaces.includeEmptyLines" = "true"
"trailing-spaces.trimOnSave" = "true"
"trailing-spaces.syntaxIgnore" = "[\"markdown\"]"
"files.associations" = """
  {
    "*.json": "json",
    "extensions.json": "jsonc",
    "settings.json": "jsonc",
    ".eslintrc*.json": "jsonc",
    "tsconfig*.json": "jsonc",
    "*.html": "html"
  }
"""
"files.exclude" = """
  {
    "**/.git": true,
    "**/.svn": true,
    "**/.hg": true,
    "**/CVS": true,
    "**/.DS_Store": true,
    "**/Thumbs.db": true,
    "build": true,
    "**/node_modules": false,
    "*.zip": true,
    "**/dist/**/*.js": false,
    "**/dist/**/*.map": true,
    "**/src/react-app-env.d.ts": true
  }
"""
"search.exclude" = """
  {
    "**/node_modules": true,
    "**/bower_components": true,
    "**/*.code-search": true,
    "*.lock": true,
    "package-lock.json": true,
  }
"""
